// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace TestChat.Core.Models.ViewModels
{
    public partial class UserChatViewModel
    {
        public Guid Id { get; set; }
        public string UserInfo { get; set; }
        public Guid SenderId { get; set; }
        public Guid RecieverId { get; set; }
        public string Message { get; set; }
        public string MessageTime { get; set; }
    }
}