USE [master]
GO
/****** Object:  Database [TestChat]    Script Date: 1/28/2021 5:48:16 PM ******/
CREATE DATABASE [TestChat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TestChat', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestChat.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TestChat_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\TestChat_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [TestChat] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TestChat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TestChat] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TestChat] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TestChat] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TestChat] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TestChat] SET ARITHABORT OFF 
GO
ALTER DATABASE [TestChat] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TestChat] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TestChat] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TestChat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TestChat] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TestChat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TestChat] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TestChat] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TestChat] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TestChat] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TestChat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TestChat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TestChat] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TestChat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TestChat] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TestChat] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TestChat] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TestChat] SET RECOVERY FULL 
GO
ALTER DATABASE [TestChat] SET  MULTI_USER 
GO
ALTER DATABASE [TestChat] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TestChat] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TestChat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TestChat] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TestChat] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TestChat] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'TestChat', N'ON'
GO
ALTER DATABASE [TestChat] SET QUERY_STORE = OFF
GO
USE [TestChat]
GO
/****** Object:  Table [dbo].[UserChats]    Script Date: 1/28/2021 5:48:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserChats](
	[Id] [uniqueidentifier] NOT NULL,
	[SenderId] [uniqueidentifier] NOT NULL,
	[RecieverId] [uniqueidentifier] NOT NULL,
	[Message] [varchar](max) NOT NULL,
	[MessageTime] [datetime] NOT NULL,
	[ReadStatus] [bit] NOT NULL,
 CONSTRAINT [PK_UserChats] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 1/28/2021 5:48:16 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [uniqueidentifier] NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[Status] [bit] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UserChats] ADD  CONSTRAINT [DF_UserChats_ReadStatus]  DEFAULT ((1)) FOR [ReadStatus]
GO
ALTER TABLE [dbo].[Users] ADD  CONSTRAINT [DF_Users_Status]  DEFAULT ((1)) FOR [Status]
GO
ALTER TABLE [dbo].[UserChats]  WITH CHECK ADD  CONSTRAINT [FK_UserChats_Receiver] FOREIGN KEY([RecieverId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[UserChats] CHECK CONSTRAINT [FK_UserChats_Receiver]
GO
ALTER TABLE [dbo].[UserChats]  WITH CHECK ADD  CONSTRAINT [FK_UserChats_Sender] FOREIGN KEY([SenderId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[UserChats] CHECK CONSTRAINT [FK_UserChats_Sender]
GO
USE [master]
GO
ALTER DATABASE [TestChat] SET  READ_WRITE 
GO
